### ISSUE TITLE
Changing output's names

### ISSUE THREAD

**Issue by waxfingers** [lvml/mpv-plugin-excerpt#4]
If I want the excerpts to retain the original file's name plus a suffix, something like: "Apocalypse_Now_Redux_excerpt_000.mp4", "Apocalypse_Now_Redux_excerpt_001.mp4", etc.
Where would I change that, in the excerpt_copy or the lua script? 
BTW thank you for a great script =)

**Comment by lvml** [comment]
On 11/22/2016 02:38 PM, waxfingers wrote:

> If I want the excerpts to retain the original file's name plus a suffix
> Where would I change that, in the excerpt_copy or the lua script?

The lua script would be the right place, as there the logic is located
to check that the generated filename is actually a new one, and does
not accidently overwrite an existing file.

**Comment by lvml** [comment]
More specifically, look at the code here:
https://github.com/lvml/mpv-plugin-excerpt/blob/master/excerpt.lua#L107

**Comment by ashfinal** [comment]
```
local file_prefix = mp.get_property("filename/no-ext”)
local fname = “”
for i=0,999 do
    local f = string.format(file_prefix .. "_excerpt_%03d.mp4", i)
```

This may do the work. : )

**Comment by lvml** [comment]
You can certainly use that for your case, but for a code merge it would need to be optional to use the name of the input file as a prefix. For my standard use case, for example, input files are just "numbered" files from my camera. It would be awkward to use those camera record names as part of the output file name.

**Comment by waxfingers** [comment]
```
local file_prefix = mp.get_property("filename/no-ext")
local fname = ""
for i=0,999 do
    local f = string.format(file_prefix .. "_excerpt_%03d.mp4", i)
```
@ashfinal I really appretiate you figuring this out, I'ld have never got there =) In the beggining didn't work, but quickly understood it was 'cause of  the quotes. **THANK YOU**

@lvml I also want to thank you for pointing out the spot and the useful script. In my personal case, I'm reviewing footage, loads of them and I want to be able to go through as much as possible, trimming the fat; if I don't have the source file reference name, it would be almost impossible to figure out which excerpt  corresponds to which source file, main goal is delete original files. Thank you gentlemen you rock =)

**Comment by ashfinal** [comment]
@lvml Yes, use case may be different. I fork this repository and change some to adapt to my need. And  your work are really appreciated. 👍 

@waxfingers Glad to hear it works. : )
