### ISSUE TITLE
bash on windows 10

### ISSUE THREAD

**Issue by ghost** [lvml/mpv-plugin-excerpt#5]
Now that windows 10 has bash, is there a way to get this working on windows?

**Comment by lvml** [comment]
I cannot comment on Windows 10, as I have/use no computers running Windows.

But some other user once forked this repository, deriving a version that seems to target Windows. see: https://github.com/pussinboot/mpv-plugin-excerpt/commit/a572be976caa13036802babcac18c52c9c740b61
