### ISSUE TITLE
[Question] Burning subtitles

### ISSUE THREAD

**Issue by pascalo7** [lvml/mpv-plugin-excerpt#7]
How would i go about having the script also burn the subs from the video files onto the video so when it is uploaded onto something like streamable it will still show the subtitles of the file.

**Comment by lvml** [comment]
On 07/25/2017 02:53 AM, Pascal wrote:
> How would i go about having the script also burn the subs from the video files onto the video

This is a question not really related to "mpv" or "mpv-plugin-excerpt" -
please consult the ffmpeg documentation to find options for such
(which you could then use in the excerpt_copy script, or separately).

I have no experience with "burning subtitles", but you may want
to look at ffmpeg filters like "subtitles" or "overlay":

https://ffmpeg.org/ffmpeg-all.html#subtitles-1
https://ffmpeg.org/ffmpeg-all.html#overlay-1
