### ISSUE TITLE
Failed excerpt clipping doesn't trigger an error

### ISSUE THREAD

**Issue by danlamanna** [lvml/mpv-plugin-excerpt#8]
I'm unsure that these lines are ever being executed:
https://github.com/lvml/mpv-plugin-excerpt/blob/92c1fc14f1b1d6d62be3f2888a15896e26400b4a/excerpt.lua#L198-L202

I clipped several videos on a disk that was full and all of them were considered "success" despite the files being empty. If I actually change the excerpt shell script to just `exit 1` at the top, the plugin still seems to think everything is getting clipped correctly.

Another easy way to test this is to just replace the `excerpt_copy` arg with `/bin/false`.

**Comment by lvml** [comment]
Good observation! - I could reproduce this issue, should be fixed with https://github.com/lvml/mpv-plugin-excerpt/commit/dd628c1f799cd7fe0602c0411a04ac357b2a368f
